# Generated by Django 5.2.6 on 2025-09-11 15:56

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("source_name", models.CharField(max_length=100)),
                ("rendered", models.CharField(blank=True, max_length=200)),
                ("json_file", models.FileField(default="tt", upload_to="json_files")),
                (
                    "source_proxy",
                    models.FileField(default="", upload_to="game_edit/previews"),
                ),
                ("slug", models.SlugField(default="")),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(default="")),
            ],
        ),
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("short_name", models.CharField(max_length=14)),
                ("date", models.DateField()),
                ("place", models.CharField(default="", max_length=200)),
                ("JTR", models.CharField(blank=True, default="", max_length=200)),
                (
                    "tugeny_link",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "color",
                    colorfield.fields.ColorField(
                        default="#0000", image_field=None, max_length=25, samples=None
                    ),
                ),
                ("source_dir", models.CharField(default="-", max_length=200)),
                ("slug", models.SlugField(default="")),
            ],
        ),
        migrations.CreateModel(
            name="Cut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type_cut",
                    models.CharField(
                        choices=[
                            ("MAN", "manual"),
                            ("VID", "from video"),
                            ("XML", "from XML"),
                            ("ML", "from ML"),
                            ("X", "others"),
                        ],
                        max_length=50,
                    ),
                ),
                ("json_file", models.FileField(default="tt", upload_to="json_files")),
                ("slug", models.SlugField(default="")),
                (
                    "game",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="game_edit.game",
                    ),
                ),
            ],
        ),
    ]
