# Generated by Django 5.2.6 on 2025-09-11 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("game_edit", "0001_initial"),
        ("miniatures", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="logo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="miniatures.teamlogo",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="team1",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Team1",
                to="game_edit.team",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="team2",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Team2",
                to="game_edit.team",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="game_edit.tournament"
            ),
        ),
    ]
