# Generated by Django 5.2.7 on 2026-05-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_tournament_drive_dir_split"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cut",
            name="type_cut",
            field=models.CharField(
                choices=[
                    ("MAN", "manual"),
                    ("VID", "from video"),
                    ("XML", "from XML"),
                    ("otio", "from otio json file"),
                    ("ML", "from ML"),
                    ("X", "others"),
                ],
                max_length=50,
            ),
        ),
    ]
