# Generated by Django 5.2.14 on 2026-06-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_cut_type_cut"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cut",
            name="type_cut",
            field=models.CharField(
                choices=[
                    ("MAN", "manual"),
                    ("VID", "from video"),
                    ("XML", "from XML"),
                    ("OTIO", "from OTIO json file"),
                    ("ML", "from ML"),
                    ("X", "others"),
                ],
                max_length=50,
            ),
        ),
    ]
