# Generated by Django 5.2.14 on 2026-06-02 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_alter_cut_game"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cut",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cuts",
                to="core.game",
            ),
        ),
    ]
