# Generated by Django 5.2.14 on 2026-06-10 14:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_render_queue_split_ffmpeg"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(blank=True, default="", max_length=150)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "created"),
                            ("RENDERING", "rendering"),
                            ("READY", "ready"),
                            ("FAILED", "failed"),
                        ],
                        default="CREATED",
                        max_length=20,
                    ),
                ),
                ("duration", models.FloatField(blank=True, null=True)),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "game_edit_video",
            },
        ),
        migrations.CreateModel(
            name="RenderQueueItemArchive",
            fields=[
                (
                    "renderqueueitemffmpeg_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.renderqueueitemffmpeg",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.game"
                    ),
                ),
            ],
            bases=("core.renderqueueitemffmpeg",),
        ),
        migrations.AddField(
            model_name="cut",
            name="video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cuts",
                to="core.video",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="games",
                to="core.video",
            ),
        ),
        migrations.CreateModel(
            name="VideoFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            ("low", "low"),
                            ("medium", "medium"),
                            ("high", "high"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("mp4", "mp4")], default="mp4", max_length=10
                    ),
                ),
                ("path", models.CharField(max_length=512)),
                ("size", models.PositiveBigIntegerField(blank=True, null=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="core.video",
                    ),
                ),
            ],
            options={
                "db_table": "game_edit_video_file",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("video", "quality", "format"),
                        name="unique_video_file_quality_format",
                    )
                ],
            },
        ),
    ]
