# Generated by Django 5.2.14 on 2026-06-10 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_video_renderqueueitemarchive_cut_video_game_video_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cut",
            name="video",
        ),
        migrations.RemoveField(
            model_name="game",
            name="video",
        ),
        migrations.AddField(
            model_name="video",
            name="cut",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video",
                to="core.cut",
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="game",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video",
                to="core.game",
            ),
        ),
    ]
