# Generated by Django 5.2.14 on 2026-06-10 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_remove_cut_video_remove_game_video_video_cut_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="video",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("game__isnull", True), ("cut__isnull", True), _connector="OR"
                ),
                name="video_has_at_most_one_owner",
            ),
        ),
    ]
