# Generated by Django 5.2.14 on 2026-06-11 09:39

import django.db.models.deletion
from django.db import migrations, models


def forwards(apps, schema_editor):
    Game = apps.get_model("core", "Game")
    Cut = apps.get_model("core", "Cut")
    Video = apps.get_model("core", "Video")

    for video in Video.objects.select_related("game", "cut").all():
        if video.game_id is not None:
            game = video.game
            if game.video_proxy_id is not None and game.video_proxy_id != video.pk:
                raise RuntimeError(
                    f"Game {game.pk} already linked to Video {game.video_proxy_id}, "
                    f"cannot link to Video {video.pk}."
                )
            game.video_proxy_id = video.pk
            game.save(update_fields=["video_proxy"])

        if video.cut_id is not None:
            cut = video.cut
            if cut.rendered_videos_id is not None and cut.rendered_videos_id != video.pk:
                raise RuntimeError(
                    f"Cut {cut.pk} already linked to Video {cut.rendered_videos_id}, "
                    f"cannot link to Video {video.pk}."
                )
            cut.rendered_videos_id = video.pk
            cut.save(update_fields=["rendered_videos"])


def backwards(apps, schema_editor):
    Game = apps.get_model("core", "Game")
    Cut = apps.get_model("core", "Cut")
    Video = apps.get_model("core", "Video")

    for game in Game.objects.exclude(video_proxy__isnull=True).select_related("video_proxy"):
        video = game.video_proxy
        video.game_id = game.pk
        video.save(update_fields=["game"])

    for cut in Cut.objects.exclude(rendered_videos__isnull=True).select_related("rendered_videos"):
        video = cut.rendered_videos
        video.cut_id = cut.pk
        video.save(update_fields=["cut"])




class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_video_video_has_at_most_one_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="cut",
            name="rendered_videos",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cuts",
                to="core.video",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="video_proxy",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="games",
                to="core.video",
            ),
        ),
        migrations.RunPython(forwards, backwards),
    ]
