# Generated by Django 5.2.14 on 2026-06-11 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_cut_rendered_videos_game_video_proxy"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="video",
            name="video_has_at_most_one_owner",
        ),
        migrations.RemoveField(
            model_name="cut",
            name="rendered_video",
        ),
        migrations.RemoveField(
            model_name="video",
            name="cut",
        ),
        migrations.RemoveField(
            model_name="video",
            name="game",
        ),
    ]
