# Generated by Django 5.2.14 on 2026-06-11 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_remove_video_video_has_at_most_one_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cut",
            name="rendered_videos",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cut",
                to="core.video",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="video_proxy",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="game",
                to="core.video",
            ),
        ),
    ]
