# Generated by Django 5.2.14 on 2026-06-11 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_alter_cut_rendered_videos_alter_game_video_proxy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="rendered",
        ),
        migrations.RemoveField(
            model_name="game",
            name="source_proxy",
        ),
    ]
