# Generated by Django 5.2.14 on 2026-06-11 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_remove_game_rendered_remove_game_source_proxy"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cut",
            old_name="rendered_videos",
            new_name="rendered_video",
        ),
    ]
