# Generated by Django 5.2.14 on 2026-06-11 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_rename_rendered_videos_cut_rendered_video"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="videofile",
            name="unique_video_file_quality_format",
        ),
    ]
