# Generated by Django 5.2.14 on 2026-07-01 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_remove_videofile_unique_video_file_quality_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="archive_video",
            field=models.ForeignKey(
                blank=True,
                help_text="Vidéo haute qualité utilisée comme archive/master pour les encodages de ce match.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="game_archive",
                to="core.video",
            ),
        ),
    ]
