# Generated by Django 5.2.14 on 2026-07-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_game_archive_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="renderqueueitembase",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("CUT_RENDER", "cut_render"),
                    ("GAME_PROXY", "game_proxy"),
                    ("GEN_CUT", "gen_cut"),
                    ("game_archive", "Game Archive"),
                ],
                default="CUT_RENDER",
                max_length=20,
            ),
        ),
        migrations.AlterModelTable(
            name="renderqueueitemarchive",
            table="game_edit_render_queue_archive",
        ),
    ]
