# Generated by Django 5.2.14 on 2026-08-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_alter_renderqueueitembase_job_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="videofile",
            name="fps",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="renderqueueitembase",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("CUT_RENDER", "cut_render"),
                    ("GAME_PROXY", "game_proxy"),
                    ("GEN_CUT", "gen_cut"),
                    ("GAME_ARCHIVE", "game_archive"),
                ],
                default="CUT_RENDER",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="videofile",
            name="quality",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("low_av1", "low_av1"),
                    ("medium_av1", "medium_av1"),
                    ("high_av1", "high_av1"),
                    ("archive", "archive"),
                ],
                max_length=10,
            ),
        ),
    ]
