# Generated by Django 5.2.14 on 2026-09-11 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_videofile_fps"),
    ]

    operations = [
        migrations.AddField(
            model_name="cut",
            name="curves_file",
            field=models.FileField(blank=True, default="", upload_to="curves/"),
        ),
        migrations.AlterField(
            model_name="renderqueueitembase",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("CUT_RENDER", "cut_render"),
                    ("GAME_PROXY", "game_proxy"),
                    ("GEN_CUT", "gen_cut"),
                    ("GAME_ARCHIVE", "game_archive"),
                    ("ML_CUT", "ml_cut"),
                ],
                default="CUT_RENDER",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="RenderQueueItemMlCut",
            fields=[
                (
                    "renderqueueitembase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.renderqueueitembase",
                    ),
                ),
                ("run_name", models.CharField(blank=True, default="", max_length=100)),
                ("threshold_in", models.FloatField(default=0.5)),
                ("threshold_out", models.FloatField(default=0.7)),
                ("min_gap", models.FloatField(default=30.0)),
                ("snap", models.BooleanField(default=True)),
                ("report", models.TextField(blank=True, default="")),
                (
                    "cut",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.cut"
                    ),
                ),
            ],
            options={
                "db_table": "game_edit_render_queue_ml_cut",
            },
            bases=("core.renderqueueitembase",),
        ),
    ]
