# Generated by Django 5.2.14 on 2026-09-15 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_game_match_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="video_metadata",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="game",
                to="core.videometadata",
            ),
        ),
    ]
