# Generated by Django 5.2.14 on 2026-09-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_game_schedule_numbers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videofile",
            name="quality",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("low_av1", "low_av1"),
                    ("medium_av1", "medium_av1"),
                    ("high_av1", "high_av1"),
                    ("youtube", "youtube"),
                    ("archive", "archive"),
                ],
                max_length=10,
            ),
        ),
    ]
