# Generated by Django 5.2.6 on 2025-09-11 15:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("game_edit", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamLogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("short_name", models.CharField(max_length=10)),
                (
                    "image",
                    models.ImageField(
                        default="default.png", upload_to="miniatures/logos"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TmpImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("date", models.DateField(auto_now_add=True)),
                ("image", models.ImageField(default="default.png", upload_to="tmp")),
            ],
        ),
        migrations.CreateModel(
            name="VideoMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("tc", models.FloatField(default=0)),
                ("video_name", models.CharField(blank=True, max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "publication_date",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                (
                    "base_image",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="base_image",
                        to="miniatures.tmpimage",
                    ),
                ),
                (
                    "miniature_image",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="miniature",
                        to="miniatures.tmpimage",
                    ),
                ),
                (
                    "team1",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team1",
                        to="miniatures.teamlogo",
                    ),
                ),
                (
                    "team2",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team2",
                        to="miniatures.teamlogo",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="miniatures",
                        to="game_edit.tournament",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "tournament")},
            },
        ),
        migrations.CreateModel(
            name="YTVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=150)),
                ("videoId", models.CharField(max_length=50, unique=True)),
                ("pub_date", models.DateTimeField(default=datetime.date.today)),
                ("privacyStatus", models.CharField(default="", max_length=150)),
                (
                    "linkedVideo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="YTlink",
                        to="miniatures.videometadata",
                    ),
                ),
            ],
        ),
    ]
