# Generated by Django 5.2.6 on 2025-09-12 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("miniatures", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ytvideo",
            old_name="linkedVideo",
            new_name="linked_video",
        ),
        migrations.RenameField(
            model_name="ytvideo",
            old_name="privacyStatus",
            new_name="privacy_status",
        ),
        migrations.RenameField(
            model_name="ytvideo",
            old_name="pub_date",
            new_name="publication_date",
        ),
        migrations.RenameField(
            model_name="ytvideo",
            old_name="videoId",
            new_name="video_id",
        ),
    ]
